services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: devpwd
      POSTGRES_DB: starport
    volumes: pgdata:/var/lib/postgresql/data

  redis:
    images: redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel debug --requirepass devpwd
    volumes:
      - cache:/data

  volumes:
    pgdata:
    cache:
      driver: local
